### PR TITLE
fix fetch_result

### PR DESCRIPTION
**Pull request by domm**
It seems that calling ->{data} on the return value from
$self->serializer->deserialize($result->{result})
always returns nothing, because $result->{result} does not contain a
data-subhash.

At least I never got any data back when calling $client->receive($id).
After removing ->{data} I get data back.

I did not look too deep into the source, so I might have misunderstood
something. In this case I'd appreciate an explanation.

If this is indeed a bug, than please apply this patch.

Greeting,
domm

### CODE REVIEW

**Comment by kaare** [comment]
Interesting! 

I have a test for $client->receive($id) in worker.t, but I'd really appreciate if you could provide a failing test case.

/kaare

**Comment by domm** [comment]
ok, I'll take a look at the test and see if I can come up with a failing test (or figure out my usage mistake :-)

**Comment by domm** [comment]
ok, so it seems that cpanm decided to install Job::Machine-0.19 and I read the docs for 0.21 (on metacpan).

After tricking cpanm to install the correct version, everything does indeed work.

Some minor hickups/notes:
- I had to delete all my test tasks, because default serializer (Seral) could not handle the old JSON tasks. Maybe it would make sense to store the used serializer somewhere inside the task (this of course would only be needed when migrating to new serializers)
- also I could not find any info on Serializers in the docs (esp. that you can pass serializer and serializer_args to ->new() )

But besides that: Sorry for the mixup & thanks for the module!

Greetings,
domm

**Comment by domm** [comment]
Ah, I've now realized that Data::Serializer does indeed store the serialization class name. I assume my problem was that 0.19 stored the data without using Data::Serialzier at all..

**Comment by domm** [comment]
And back to the start: My original patch is still necessary.
To see the problem, please run t/worker_fail_if_hash_not_named_data.t against your current code.
You will see various test fails, because I choose to name the hash passed to $self->reply 'foo' instead of 'data'.
So either you have to force users to pass their data as values of a hash key named 'data', or apply my patch.

But forcing 'data' is not what's in the docs:
$client->send({foo => 'bar'});
$self->reply({baz => 'Yeah!'})
etc

Unfortunately, the test did work, but was broken itself...

Do you see my point?

Greetings,
domm

**Comment by kaare** [comment]
Hi Thomas

Ouch, that's awful. I guess it's because I have a pod instead of a pm 
with the same name as the dist. Metacpan reads the makefile, perhaps the 
indexer of search.cpan doesn't (?)

Some more comments:

It ought to delete the tests by itself. Not sure what's going on there.
I'll look into the serializer parameters documentation, and the 
"original" problem you describe in other mails as soon as I get a little 
time. Hopefully tomorrow.

/kaare

**Comment by kaare** [comment]
Hi Thomas

I found time this evening. I agree with you that the module assumes too 
much about the names. The current github will be 0.22 if you don't find 
anything criminal.

/kaare

**Comment by domm** [comment]
ok, I'll give the current master a try right now!

**Comment by domm** [comment]
works, so IMO you can push a new release

**Pull request merged**
